### ISSUE TITLE
Leveraging persistor

### ISSUE THREAD

**Issue by kylemh** [fazlulkarimweb/with-next-redux-wrapper-redux-persist#2]
Thanks for your boilerplate, it's helped me quite a bit.

One thing I'm not certain of is how to leverage the persistor manually.

It's applied as a key onto the `store` object that's return part of the `makeStore` method like so: `store.__persistor`.

I ended up doing this in my `_app` instead:
```js
const store = useStore();
const persistor = persistStore(store);
```

but both of our solutions don't provide access to the `__persistor` value when I want to do something like `persistor.flush()`.

Any ideas?

**Comment by fazlulkarimweb** [comment]
Sorry for the late reply. I think, leveraging the persistor manually may create unwanted side effects in server-side rendering. Even the author of the framework commented the store.__persistor method as a nasty hack! I don't have any idea about the current scenario of your codebase btw. But this is not a very good idea to flush manually if we follow the principal. Local storage based bugs are very hard to solve because they happened on the laptops and computers of random people!
